### ISSUE TITLE
Error while building toolchain.

### ISSUE THREAD

**Issue by JustVic** [lutoma/xelix#93]
Trying to build an OS. But while building toolchain("make -C toolchain") I got this error:

checking for shl_load... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.

Anyone know how to fix it?

**Comment by lutoma** [comment]
I don't test building the toolchain on a freshly cloned repository nearly as frequently as I should so it breaks from time to time (or only works in my specific setup).

I'll try doing that now and see if I can fix any errors I run into. In the meantime, what distribution are you trying to build the toolchain on, and can you upload the complete log somewhere?

From the error it sounds like the error occured while building GCC, did your binutils build succeed?

**Comment by lutoma** [comment]
Turns out the issue was related to libstdc++ which is not really required to build the kernel itself anyway, only some experimental userland stuff. I've disabled that for now and made some other fixes in e5593c0.

I've also added some stuff to the documentation on required autoconf/automake versions: https://xelix.org/compiling/ -- Those will probably be relevant for you too

With that it should work now, can you give it another try? (You may have to delete the `build`, `download` and `local` subdirectories in the `toolchain` dir)

**Comment by JustVic** [comment]
Thanks for the quick response. I'll try again.

**Comment by JustVic** [comment]
I made correct symlinks for autoconf and autoreconf and toolchain was built good. But I got problems after when building the system(#94).

**Comment by lutoma** [comment]
Alright, good to hear! Just added a response to your other issue. If you're up for it we could also work this out on Matrix/IRC/Signal or something, might be easier than going back and forth in Github issues.
